/* Author：bianpengfei Automatically generated by './bin/build-entry-nodejs.js' */

const getIpAddrSync = require('./getIpAddrSync.js')
const readDirStructureSync = require('./readDirStructureSync.js')

const version = '2.1.0'

module.exports = {
  version,
  getIpAddrSync,
  readDirStructureSync
}
